### ISSUE TITLE
Problems with getting Private key as data

### ISSUE THREAD

**Issue by pavlem** [4taras4/RSASwiftGenerator#3]
Hello, 
Nice library :). 
I am using it with other library meant for JWT -> https://github.com/IBM-Swift/Swift-JWT which uses your library for the part of generating private keys. 

Unfortunately, I am having some problems and I do not know is it this related to his or your library. 

You have methods 
```
let getPublicKeyData = RSASwiftGenerator.shared.getPublicKeyData()
let getPublicKeyReference = RSASwiftGenerator.shared.getPublicKeyReference()
let getPrivateKeyReference = RSASwiftGenerator.shared.getPrivateKeyReference()
```
And I get an expected results from them (please see the attachment) 

here is the custom part I tried for getting private key as raw Data since there is no ".getPrivateKeyData()"

```
var dataPtr:CFTypeRef?
        let query: [String: Any] = [
            kSecClass as String: kSecClassKey,
            kSecAttrApplicationTag as String: "MY.BUNDLE.ID",
            kSecReturnData as String: true
        ]

        let qResult = SecItemCopyMatching(query as CFDictionary, &dataPtr)
        let data = dataPtr as! Data
        let base64PublicKey = data.base64EncodedString()
```

Then when I tried signing with privateKey my stuff, I get an error:
SwiftJWT.JWTError(localizedDescription: "Provided private key could not be used to sign JWT", internalError: SwiftJWT.(unknown context at 0x10d9ae418).InternalError.invalidPrivateKey)

I am not sure is it his library, yours or am I doing something wrong. Concretely, what do you advise on how to get private key as Data to be sure that part is working.

**Comment by 4taras4** [comment]
hello, i checked this library and they are not use my lib for generating keys. Ask you problem to pod creator witch you use

**Comment by pavlem** [comment]
Yes, I just saw that I am using your lib for generating keys and theirs for JWT only, sorry. 

I generated PRIV and PUB key on my mac as PEM with these commands:

```
ssh-keygen -t rsa -b 2048 -m PEM -f jwt.key
openssl rsa -in jwt.key -pubout -outform PEM -out jwt.key.pub 
```

then I got references of those keys in my project as Data with these:

```
        let privateKeyPath = URL(fileURLWithPath: "/Users/pm/.ssh/jwt.key")
        let privKey: Data = try! Data(contentsOf: privateKeyPath, options: .alwaysMapped); 
        let pubKeyPath = URL(fileURLWithPath: "/Users/pm/.ssh/jwt.key.pub")
        let pubKey: Data = try! Data(contentsOf: pubKeyPath, options: .alwaysMapped)
```

And that mentioned library worked, so I am thinking that I am not getting correctly the Data type of the private key your lib generated when I am using it. Can you please advise how to do it since you do not have something like

```
getPrivateKeyData()
```

**Comment by 4taras4** [comment]
> First of all you need to contains to keys to keichain and after that use it , like KeySec

**Comment by 4taras4** [comment]
https://stackoverflow.com/questions/10579985/how-can-i-get-seckeyref-from-der-pem-file
